//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectPrivacy.SSHManager.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PerfectPrivacy.SSHManager.lang.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string connection {
            get {
                return ResourceManager.GetString("connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection with this name already exists. Please choose another name..
        /// </summary>
        internal static string connectionExists {
            get {
                return ResourceManager.GetString("connectionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a.
        /// </summary>
        internal static string createA {
            get {
                return ResourceManager.GetString("createA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid hostname or IP.
        /// </summary>
        internal static string enterValidHostname {
            get {
                return ResourceManager.GetString("enterValidHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid local port between 1 and 65535.
        /// </summary>
        internal static string enterValidLocalPort {
            get {
                return ResourceManager.GetString("enterValidLocalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid remote port between 1 and 65535.
        /// </summary>
        internal static string enterValidRemotePort {
            get {
                return ResourceManager.GetString("enterValidRemotePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid session name.
        /// </summary>
        internal static string enterValidSessionName {
            get {
                return ResourceManager.GetString("enterValidSessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid Name.
        /// </summary>
        internal static string enterValidUsername {
            get {
                return ResourceManager.GetString("enterValidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for connection.
        /// </summary>
        internal static string forConnection {
            get {
                return ResourceManager.GetString("forConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarding.
        /// </summary>
        internal static string forwarding {
            get {
                return ResourceManager.GetString("forwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is active! Disconnect first..
        /// </summary>
        internal static string isActiveDisconnect {
            get {
                return ResourceManager.GetString("isActiveDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string isconnectedNo {
            get {
                return ResourceManager.GetString("isconnectedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string isconnectedYes {
            get {
                return ResourceManager.GetString("isconnectedYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is no longer available, sorry..
        /// </summary>
        internal static string noLongerAvailable {
            get {
                return ResourceManager.GetString("noLongerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to port.
        /// </summary>
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers available.
        /// </summary>
        internal static string serversAvailable {
            get {
                return ResourceManager.GetString("serversAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to servers local.
        /// </summary>
        internal static string serversLocal {
            get {
                return ResourceManager.GetString("serversLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Connection?.
        /// </summary>
        internal static string sureDelete {
            get {
                return ResourceManager.GetString("sureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tedst en.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usable at.
        /// </summary>
        internal static string usableAt {
            get {
                return ResourceManager.GetString("usableAt", resourceCulture);
            }
        }
    }
}
